### ISSUE TITLE
Repeated events with every day on selected time

### ISSUE THREAD

**Issue by Liiion911** [alordash/date-parser#8]
Hi, i don't understand this

> каждый день в 23.30 текст
```
target_date: { ... hours: 23, minutes: 30, ... }
period_time: { ... dates: 1, ... }
```
it's good.

> каждый 1 день в 23.30 текст
```
target_date: { all properties undefined }
period_time: { ... dates: 1, hours: 23, minutes: 30, ... }
```
i think it's not good...

Reproduce this bug on Smart Scheduler telegram bot:
![image](https://user-images.githubusercontent.com/5536187/111533605-0551bc00-8778-11eb-9f72-a8daa718895b.png)

P.S.: 
![image](https://user-images.githubusercontent.com/5536187/111533689-20243080-8778-11eb-92c4-dcaf31e82c98.png)
only for joke

**Comment by alordash** [comment]
Fixed bug [here](https://github.com/alordash/date-parser/commit/7d168864d3d24a48894eb9c6dbe0b9505c5e7db1).
Fixed joke bug [here](https://github.com/alordash/date-parser/commit/be40fcb470deba59df3799cd0caa2407f0978be0).

Published [bug-fix release](https://github.com/alordash/date-parser/releases/tag/v2.1.8).

**Comment by Liiion911** [comment]
Thx for fast fix!

Thank you for your amazing lib!
